@@ -0,0 +1,13 @@
env:
  browser: true
   node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
# rules: {
  
#   "import/extensions": "off",
#   "no-console": "off"
 
# }