@@ -0,0 +1,13 @@
env:
  browser: true
   node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
      "linebreak-style": 0,
  "import/extensions": "off",
  "no-console": "off",
  "indent": ["error", 4]
}